# Generated by Django 6.0.3 on 2026-03-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiroia',
            name='cortes_gerados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
