# Generated by Django 6.0.3 on 2026-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_roteiroia_cortes_gerados'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiroia',
            name='cortes_original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
