# Generated by Django 6.0.3 on 2026-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_roteiroia_cortes_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiroia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente ⚪'), ('gravando', 'Gravando 🎥'), ('editando', 'Editando ✂️'), ('postado', 'Postado ✅')], default='pendente', max_length=20),
        ),
    ]
