# Generated by Django 6.0.3 on 2026-03-14 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_historicocanal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicho', models.CharField(default='Tecnologia', max_length=50)),
                ('vids_dia', models.IntegerField(default=1)),
                ('vids_semana', models.IntegerField(default=7)),
                ('melhor_horario', models.CharField(default='19:00', max_length=100)),
                ('dia_pico', models.CharField(default='Terça-feira', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
