# Generated by Django 6.0.3 on 2026-03-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
