# Generated by Django 6.0.3 on 2026-03-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_perfil_nome_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idioma_ia',
            field=models.CharField(default='pt', max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tema',
            field=models.CharField(default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tom_voz_ia',
            field=models.CharField(default='casual', max_length=30),
        ),
    ]
